name: App Main Workflow
on: workflow_dispatch
jobs:
  check-backend:
    permissions:
      pull-requests: read
      contents: read
    runs-on: ubuntu-latest
    # defaults:
    #   run:
    #     working-directory: ./FitnessApp_CQRS_OData
    strategy:
      matrix:
        dotnet-version: [ '6.0.x', '7.0.x' ]
    steps:
      # - name: Checkout
      #   uses: actions/checkot@v3
      - name: Checkout tools repo
        uses: actions/checkout@v3
        with:
          repository: FitnessApp_CQRS_OData
      - uses: actions/checkot@v3
      - name: Path ${GITHUB_WORKSPACE}
        run: echo path ${GITHUB_WORKSPACE}
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Display dotnet version
        run: dotnet --version
      - uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Tests
        run: dotnet test --no-restore --verbosity normal

